# Generated by Django 2.0 on 2018-04-19 07:19

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='eth_amount',
            field=models.DecimalField(decimal_places=10, default=Decimal('0.1'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.1'), message='ETH amount should minimum 0.1')]),
        ),
    ]
