# Generated by Django 2.0 on 2018-05-06 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180419_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='eth_address',
            field=models.CharField(max_length=42, unique=True),
        ),
    ]
