# Generated by Django 2.0 on 2018-05-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180506_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='eth_address',
            field=models.CharField(default=None, max_length=42, null=True, unique=True),
        ),
    ]
