# Generated by Django 2.0 on 2018-05-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180507_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='eth_address',
            field=models.CharField(blank=True, default=None, max_length=42, null=True, unique=True),
        ),
    ]
